const donors = [
  {
    id: 1,
    name: "Ali",
    Bloodgroup: "O+",
    city: "Lahore",
    phone: "03000000001",
    email: "ali.d@example.com",
    age: 30,
  },
  {
    id: 2,
    name: "Sharafat",
    Bloodgroup: "O-",
    city: "Karachi",
    phone: "03000000002",
    email: "sharafat.k@example.com",
    age: 45,
  },
  {
    id: 3,
    name: "Malik",
    Bloodgroup: "AB-",
    city: "Islamabad",
    phone: "03000000003",
    email: "malik.i@example.com",
    age: 28,
  },
  {
    id: 4,
    name: "Sara",
    Bloodgroup: "A-",
    city: "Faisalabad",
    phone: "03000000004",
    email: "sara.f@example.com",
    age: 34,
  },
  {
    id: 5,
    name: "Ahmed",
    Bloodgroup: "B+",
    city: "Rawalpindi",
    phone: "03000000005",
    email: "ahmed.r@example.com",
    age: 50,
  },
  {
    id: 6,
    name: "Zainab",
    Bloodgroup: "AB+",
    city: "Multan",
    phone: "03000000006",
    email: "zainab.m@example.com",
    age: 22,
  },
  {
    id: 7,
    name: "Usman",
    Bloodgroup: "O-",
    city: "Gujranwala",
    phone: "03000000007",
    email: "usman.g@example.com",
    age: 39,
  },
  {
    id: 8,
    name: "Fatima",
    Bloodgroup: "A+",
    city: "Sialkot",
    phone: "03000000008",
    email: "fatima.s@example.com",
    age: 27,
  },
  {
    id: 9,
    name: "Hassan",
    Bloodgroup: "B-",
    city: "Hyderabad",
    phone: "03000000009",
    email: "hassan.h@example.com",
    age: 31,
  },
  {
    id: 10,
    name: "Noor",
    Bloodgroup: "AB-",
    city: "Peshawar",
    phone: "03000000010",
    email: "noor.p@example.com",
    age: 29,
  },
  {
    id: 11,
    name: "Bilal",
    Bloodgroup: "O+",
    city: "Lahore",
    phone: "03000000011",
    email: "bilal.l@example.com",
    age: 33,
  },
  {
    id: 12,
    name: "Ayesha",
    Bloodgroup: "A+",
    city: "Quetta",
    phone: "03000000012",
    email: "ayesha.q@example.com",
    age: 26,
  },
  {
    id: 13,
    name: "Hamza",
    Bloodgroup: "B+",
    city: "Bahawalpur",
    phone: "03000000013",
    email: "hamza.b@example.com",
    age: 48,
  },
  {
    id: 14,
    name: "Mariam",
    Bloodgroup: "AB+",
    city: "Sargodha",
    phone: "03000000014",
    email: "mariam.s@example.com",
    age: 24,
  },
  {
    id: 15,
    name: "Saad",
    Bloodgroup: "O-",
    city: "Sukkur",
    phone: "03000000015",
    email: "saad.su@example.com",
    age: 36,
  },
  {
    id: 16,
    name: "Iqra",
    Bloodgroup: "A-",
    city: "Abbottabad",
    phone: "03000000016",
    email: "iqra.a@example.com",
    age: 23,
  },
  {
    id: 17,
    name: "Danish",
    Bloodgroup: "B+",
    city: "Jhelum",
    phone: "03000000017",
    email: "danish.j@example.com",
    age: 41,
  },
  {
    id: 18,
    name: "Hiba",
    Bloodgroup: "AB-",
    city: "Rahim Yar Khan",
    phone: "03000000018",
    email: "hiba.r@example.com",
    age: 25,
  },
  {
    id: 19,
    name: "Tariq",
    Bloodgroup: "O+",
    city: "Okara",
    phone: "03000000019",
    email: "tariq.o@example.com",
    age: 38,
  },
  {
    id: 20,
    name: "Nimra",
    Bloodgroup: "A+",
    city: "Gujrat",
    phone: "03000000020",
    email: "nimra.g@example.com",
    age: 32,
  },
  {
    id: 21,
    name: "Shahzaib",
    Bloodgroup: "B-",
    city: "Sahiwal",
    phone: "03000000021",
    email: "shahzaib.sa@example.com",
    age: 29,
  },
  {
    id: 22,
    name: "Lubna",
    Bloodgroup: "AB+",
    city: "Mardan",
    phone: "03000000022",
    email: "lubna.m@example.com",
    age: 43,
  },
  {
    id: 23,
    name: "Farhan",
    Bloodgroup: "O-",
    city: "Kasur",
    phone: "03000000023",
    email: "farhan.k@example.com",
    age: 35,
  },
  {
    id: 24,
    name: "Mehwish",
    Bloodgroup: "A-",
    city: "Mirpur",
    phone: "03000000024",
    email: "mehwish.m@example.com",
    age: 28,
  },
  {
    id: 25,
    name: "Junaid",
    Bloodgroup: "B+",
    city: "Nawabshah",
    phone: "03000000025",
    email: "junaid.n@example.com",
    age: 40,
  },
  {
    id: 26,
    name: "Kiran",
    Bloodgroup: "AB+",
    city: "Chiniot",
    phone: "03000000026",
    email: "kiran.c@example.com",
    age: 21,
  },
  {
    id: 27,
    name: "Waqas",
    Bloodgroup: "O+",
    city: "Sheikhupura",
    phone: "03000000027",
    email: "waqas.s@example.com",
    age: 37,
  },
  {
    id: 28,
    name: "Anum",
    Bloodgroup: "A+",
    city: "Larkana",
    phone: "03000000028",
    email: "anum.l@example.com",
    age: 25,
  },
  {
    id: 29,
    name: "Rizwan",
    Bloodgroup: "B-",
    city: "Khairpur",
    phone: "03000000029",
    email: "rizwan.k@example.com",
    age: 30,
  },
  {
    id: 30,
    name: "Hina",
    Bloodgroup: "AB-",
    city: "Tando Adam",
    phone: "03000000030",
    email: "hina.t@example.com",
    age: 33,
  },
  {
    id: 31,
    name: "Salman",
    Bloodgroup: "O+",
    city: "Dera Ghazi Khan",
    phone: "03000000031",
    email: "salman.d@example.com",
    age: 42,
  },
  {
    id: 32,
    name: "Sana",
    Bloodgroup: "A+",
    city: "Mansehra",
    phone: "03000000032",
    email: "sana.m@example.com",
    age: 26,
  },
  {
    id: 33,
    name: "Yasir",
    Bloodgroup: "B+",
    city: "Vehari",
    phone: "03000000033",
    email: "yasir.v@example.com",
    age: 49,
  },
  {
    id: 34,
    name: "Rabia",
    Bloodgroup: "AB-",
    city: "Chakwal",
    phone: "03000000034",
    email: "rabia.c@example.com",
    age: 24,
  },
  {
    id: 35,
    name: "Imran",
    Bloodgroup: "O-",
    city: "Dadu",
    phone: "03000000035",
    email: "imran.d@example.com",
    age: 31,
  },
  {
    id: 36,
    name: "Komal",
    Bloodgroup: "A-",
    city: "Jhang",
    phone: "03000000036",
    email: "komal.j@example.com",
    age: 22,
  },
  {
    id: 37,
    name: "Adeel",
    Bloodgroup: "B+",
    city: "Kotli",
    phone: "03000000037",
    email: "adeel.k@example.com",
    age: 46,
  },
  {
    id: 38,
    name: "Zoya",
    Bloodgroup: "AB+",
    city: "Attock",
    phone: "03000000038",
    email: "zoya.a@example.com",
    age: 27,
  },
  {
    id: 39,
    name: "Nabeel",
    Bloodgroup: "O+",
    city: "Mingora",
    phone: "03000000039",
    email: "nabeel.m@example.com",
    age: 30,
  },
  {
    id: 40,
    name: "Fariha",
    Bloodgroup: "A+",
    city: "Muzaffargarh",
    phone: "03000000040",
    email: "fariha.m@example.com",
    age: 29,
  },
  {
    id: 41,
    name: "Arham",
    Bloodgroup: "B-",
    city: "Jhelum",
    phone: "03000000041",
    email: "arham.j@example.com",
    age: 34,
  },
  {
    id: 42,
    name: "Mahnoor",
    Bloodgroup: "AB-",
    city: "Kamoke",
    phone: "03000000042",
    email: "mahnoor.k@example.com",
    age: 20,
  },
  {
    id: 43,
    name: "Jawad",
    Bloodgroup: "O-",
    city: "Bannu",
    phone: "03000000043",
    email: "jawad.b@example.com",
    age: 36,
  },
  {
    id: 44,
    name: "Neha",
    Bloodgroup: "A-",
    city: "Dera Ismail Khan",
    phone: "03000000044",
    email: "neha.d@example.com",
    age: 23,
  },
  {
    id: 45,
    name: "Haroon",
    Bloodgroup: "B+",
    city: "Nowshera",
    phone: "03000000045",
    email: "haroon.n@example.com",
    age: 47,
  },
  {
    id: 46,
    name: "Rida",
    Bloodgroup: "AB+",
    city: "Turbat",
    phone: "03000000046",
    email: "rida.t@example.com",
    age: 28,
  },
  {
    id: 47,
    name: "Omer",
    Bloodgroup: "O+",
    city: "Skardu",
    phone: "03000000047",
    email: "omer.s@example.com",
    age: 35,
  },
  {
    id: 48,
    name: "Aleena",
    Bloodgroup: "A+",
    city: "Gilgit",
    phone: "03000000048",
    email: "aleena.g@example.com",
    age: 31,
  },
  {
    id: 49,
    name: "Shayan",
    Bloodgroup: "B-",
    city: "Khuzdar",
    phone: "03000000049",
    email: "shayan.k@example.com",
    age: 29,
  },
  {
    id: 50,
    name: "Laiba",
    Bloodgroup: "AB-",
    city: "Mardan",
    phone: "03000000050",
    email: "laiba.m@example.com",
    age: 26,
  },
  {
    id: 51,
    name: "Noman",
    Bloodgroup: "O-",
    city: "Bahawalnagar",
    phone: "03000000051",
    email: "noman.b@example.com",
    age: 33,
  },
  {
    id: 52,
    name: "Bushra",
    Bloodgroup: "A-",
    city: "Shikarpur",
    phone: "03000000052",
    email: "bushra.s@example.com",
    age: 24,
  },
  {
    id: 53,
    name: "Sameer",
    Bloodgroup: "B+",
    city: "Zhob",
    phone: "03000000053",
    email: "sameer.z@example.com",
    age: 40,
  },
];

export default donors;
